// Code generated by "stringer -type=CBORTag -trimprefix=CBORTag"; DO NOT EDIT.

package values

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CBORTagVoidValue-128]
	_ = x[CBORTagSomeValue-130]
	_ = x[CBORTagAddressValue-131]
	_ = x[CBORTagCompositeValue-132]
	_ = x[CBORTagTypeValue-133]
	_ = x[CBORTagStringValue-135]
	_ = x[CBORTagCharacterValue-136]
	_ = x[CBORTagSomeValueWithNestedLevels-137]
	_ = x[CBORTagIntValue-152]
	_ = x[CBORTagInt8Value-153]
	_ = x[CBORTagInt16Value-154]
	_ = x[CBORTagInt32Value-155]
	_ = x[CBORTagInt64Value-156]
	_ = x[CBORTagInt128Value-157]
	_ = x[CBORTagInt256Value-158]
	_ = x[CBORTagUIntValue-160]
	_ = x[CBORTagUInt8Value-161]
	_ = x[CBORTagUInt16Value-162]
	_ = x[CBORTagUInt32Value-163]
	_ = x[CBORTagUInt64Value-164]
	_ = x[CBORTagUInt128Value-165]
	_ = x[CBORTagUInt256Value-166]
	_ = x[CBORTagWord8Value-169]
	_ = x[CBORTagWord16Value-170]
	_ = x[CBORTagWord32Value-171]
	_ = x[CBORTagWord64Value-172]
	_ = x[CBORTagWord128Value-173]
	_ = x[CBORTagWord256Value-174]
	_ = x[CBORTagFix64Value-180]
	_ = x[CBORTagFix128Value-181]
	_ = x[CBORTagUFix64Value-188]
	_ = x[CBORTagUFix128Value-189]
	_ = x[CBORTagAddressLocation-192]
	_ = x[CBORTagStringLocation-193]
	_ = x[CBORTagIdentifierLocation-194]
	_ = x[CBORTagTransactionLocation-195]
	_ = x[CBORTagScriptLocation-196]
	_ = x[CBORTagPathValue-200]
	_ = x[CBORTagPathCapabilityValue-201]
	_ = x[CBORTagPathLinkValue-203]
	_ = x[CBORTagPublishedValue-204]
	_ = x[CBORTagAccountLinkValue-205]
	_ = x[CBORTagStorageCapabilityControllerValue-206]
	_ = x[CBORTagAccountCapabilityControllerValue-207]
	_ = x[CBORTagCapabilityValue-208]
	_ = x[CBORTagPrimitiveStaticType-212]
	_ = x[CBORTagCompositeStaticType-213]
	_ = x[CBORTagInterfaceStaticType-214]
	_ = x[CBORTagVariableSizedStaticType-215]
	_ = x[CBORTagConstantSizedStaticType-216]
	_ = x[CBORTagDictionaryStaticType-217]
	_ = x[CBORTagOptionalStaticType-218]
	_ = x[CBORTagReferenceStaticType-219]
	_ = x[CBORTagIntersectionStaticType-220]
	_ = x[CBORTagCapabilityStaticType-221]
	_ = x[CBORTagUnauthorizedStaticAuthorization-222]
	_ = x[CBORTagEntitlementMapStaticAuthorization-223]
	_ = x[CBORTagEntitlementSetStaticAuthorization-224]
	_ = x[CBORTagInaccessibleStaticAuthorization-225]
	_ = x[CBORTagInclusiveRangeStaticType-230]
	_ = x[CBORTag_Count-231]
}

const _CBORTag_name = "VoidValueSomeValueAddressValueCompositeValueTypeValueStringValueCharacterValueSomeValueWithNestedLevelsIntValueInt8ValueInt16ValueInt32ValueInt64ValueInt128ValueInt256ValueUIntValueUInt8ValueUInt16ValueUInt32ValueUInt64ValueUInt128ValueUInt256ValueWord8ValueWord16ValueWord32ValueWord64ValueWord128ValueWord256ValueFix64ValueFix128ValueUFix64ValueUFix128ValueAddressLocationStringLocationIdentifierLocationTransactionLocationScriptLocationPathValuePathCapabilityValuePathLinkValuePublishedValueAccountLinkValueStorageCapabilityControllerValueAccountCapabilityControllerValueCapabilityValuePrimitiveStaticTypeCompositeStaticTypeInterfaceStaticTypeVariableSizedStaticTypeConstantSizedStaticTypeDictionaryStaticTypeOptionalStaticTypeReferenceStaticTypeIntersectionStaticTypeCapabilityStaticTypeUnauthorizedStaticAuthorizationEntitlementMapStaticAuthorizationEntitlementSetStaticAuthorizationInaccessibleStaticAuthorizationInclusiveRangeStaticType_Count"

var _CBORTag_map = map[CBORTag]string{
	128: _CBORTag_name[0:9],
	130: _CBORTag_name[9:18],
	131: _CBORTag_name[18:30],
	132: _CBORTag_name[30:44],
	133: _CBORTag_name[44:53],
	135: _CBORTag_name[53:64],
	136: _CBORTag_name[64:78],
	137: _CBORTag_name[78:103],
	152: _CBORTag_name[103:111],
	153: _CBORTag_name[111:120],
	154: _CBORTag_name[120:130],
	155: _CBORTag_name[130:140],
	156: _CBORTag_name[140:150],
	157: _CBORTag_name[150:161],
	158: _CBORTag_name[161:172],
	160: _CBORTag_name[172:181],
	161: _CBORTag_name[181:191],
	162: _CBORTag_name[191:202],
	163: _CBORTag_name[202:213],
	164: _CBORTag_name[213:224],
	165: _CBORTag_name[224:236],
	166: _CBORTag_name[236:248],
	169: _CBORTag_name[248:258],
	170: _CBORTag_name[258:269],
	171: _CBORTag_name[269:280],
	172: _CBORTag_name[280:291],
	173: _CBORTag_name[291:303],
	174: _CBORTag_name[303:315],
	180: _CBORTag_name[315:325],
	181: _CBORTag_name[325:336],
	188: _CBORTag_name[336:347],
	189: _CBORTag_name[347:359],
	192: _CBORTag_name[359:374],
	193: _CBORTag_name[374:388],
	194: _CBORTag_name[388:406],
	195: _CBORTag_name[406:425],
	196: _CBORTag_name[425:439],
	200: _CBORTag_name[439:448],
	201: _CBORTag_name[448:467],
	203: _CBORTag_name[467:480],
	204: _CBORTag_name[480:494],
	205: _CBORTag_name[494:510],
	206: _CBORTag_name[510:542],
	207: _CBORTag_name[542:574],
	208: _CBORTag_name[574:589],
	212: _CBORTag_name[589:608],
	213: _CBORTag_name[608:627],
	214: _CBORTag_name[627:646],
	215: _CBORTag_name[646:669],
	216: _CBORTag_name[669:692],
	217: _CBORTag_name[692:712],
	218: _CBORTag_name[712:730],
	219: _CBORTag_name[730:749],
	220: _CBORTag_name[749:771],
	221: _CBORTag_name[771:791],
	222: _CBORTag_name[791:822],
	223: _CBORTag_name[822:855],
	224: _CBORTag_name[855:888],
	225: _CBORTag_name[888:919],
	230: _CBORTag_name[919:943],
	231: _CBORTag_name[943:949],
}

func (i CBORTag) String() string {
	if str, ok := _CBORTag_map[i]; ok {
		return str
	}
	return "CBORTag(" + strconv.FormatInt(int64(i), 10) + ")"
}
