version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - forbidigo
    - gocritic
    - govet
    - ineffassign
    - maprange
    - misspell
    - nilerr
    - staticcheck
    - unconvert
    - unkeyed
    - unused
  settings:
    forbidigo:
      forbid:
        - pattern: ^maps.Keys.*(# has indeterminate order\.)?$
        - pattern: ^maps.Values.*(# has indeterminate order\.)?$
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - unslice
        - commentFormatting
        - exitAfterDefer
    staticcheck:
      dot-import-whitelist:
        - github.com/onflow/cadence/bbq/test_utils
        - github.com/onflow/cadence/test_utils/common_utils
        - github.com/onflow/cadence/test_utils/sema_utils
        - github.com/onflow/cadence/test_utils/runtime_utils
      checks:
        - all
        - '-S1016' # should convert ... (type ...) to ... instead of using struct literal
        - '-ST1003' # should not use underscores in Go names
        - '-ST1005' # error strings should not be capitalized. reports false positives for acronyms
        - '-QF1001' # could apply De Morgan's law
        - '-QF1008' # could remove embedded field "..." from selector
    custom:
      constructorcheck:
        path: tools/constructorcheck/constructorcheck.so
        description: reports range statements over maps
        original-url: github.com/onflow/cadence/tools/constructorcheck
      maprange:
        path: tools/maprange/maprange.so
        description: reports for-range statements over maps
        original-url: github.com/onflow/cadence/tools/maprange
      unkeyed:
        path: tools/unkeyed/unkeyed.so
        description: reports unkeyed composite literals
        original-url: github.com/onflow/cadence/tools/unkeyed
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - constructorcheck
          - maprange
          - unkeyed
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/onflow/cadence
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
