// Code generated by "stringer -type=Access"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessNotSpecified-0]
	_ = x[AccessPrivate-1]
	_ = x[AccessPublic-2]
	_ = x[AccessPublicSettable-3]
}

const _Access_name = "AccessNotSpecifiedAccessPrivateAccessPublicAccessPublicSettable"

var _Access_index = [...]uint8{0, 18, 31, 43, 63}

func (a Access) String() string {
	if a < 0 || a >= Access(len(_Access_index)-1) {
		return "Access(" + strconv.FormatInt(int64(a), 10) + ")"
	}
	return _Access_name[_Access_index[a]:_Access_index[a+1]]
}
