// Code generated by "stringer -type=ConditionKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConditionKindUnknown-0]
	_ = x[ConditionKindPre-1]
	_ = x[ConditionKindPost-2]
}

const _ConditionKind_name = "ConditionKindUnknownConditionKindPreConditionKindPost"

var _ConditionKind_index = [...]uint8{0, 20, 36, 53}

func (i ConditionKind) String() string {
	if i >= ConditionKind(len(_ConditionKind_index)-1) {
		return "ConditionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionKind_name[_ConditionKind_index[i]:_ConditionKind_index[i+1]]
}
