/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=ConditionKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConditionKindUnknown-0]
	_ = x[ConditionKindPre-1]
	_ = x[ConditionKindPost-2]
}

const _ConditionKind_name = "ConditionKindUnknownConditionKindPreConditionKindPost"

var _ConditionKind_index = [...]uint8{0, 20, 36, 53}

func (i ConditionKind) String() string {
	if i < 0 || i >= ConditionKind(len(_ConditionKind_index)-1) {
		return "ConditionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionKind_name[_ConditionKind_index[i]:_ConditionKind_index[i+1]]
}
