/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=CompositeKind"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompositeKindUnknown-0]
	_ = x[CompositeKindStructure-1]
	_ = x[CompositeKindResource-2]
	_ = x[CompositeKindContract-3]
	_ = x[CompositeKindEvent-4]
}

const _CompositeKind_name = "CompositeKindUnknownCompositeKindStructureCompositeKindResourceCompositeKindContractCompositeKindEvent"

var _CompositeKind_index = [...]uint8{0, 20, 42, 63, 84, 102}

func (i CompositeKind) String() string {
	if i < 0 || i >= CompositeKind(len(_CompositeKind_index)-1) {
		return "CompositeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompositeKind_name[_CompositeKind_index[i]:_CompositeKind_index[i+1]]
}
