// Code generated by "stringer -type=MemoryKind -trimprefix=MemoryKind"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MemoryKindUnknown-0]
	_ = x[MemoryKindBool-1]
	_ = x[MemoryKindAddress-2]
	_ = x[MemoryKindString-3]
	_ = x[MemoryKindCharacter-4]
	_ = x[MemoryKindMetaType-5]
	_ = x[MemoryKindNumber-6]
	_ = x[MemoryKindArray-7]
	_ = x[MemoryKindDictionary-8]
	_ = x[MemoryKindComposite-9]
	_ = x[MemoryKindOptional-10]
	_ = x[MemoryKindNil-11]
	_ = x[MemoryKindVoid-12]
	_ = x[MemoryKindTypeValue-13]
	_ = x[MemoryKindPathValue-14]
	_ = x[MemoryKindCapabilityValue-15]
	_ = x[MemoryKindLinkValue-16]
	_ = x[MemoryKindStorageReferenceValue-17]
	_ = x[MemoryKindEphemeralReferenceValue-18]
	_ = x[MemoryKindInterpretedFunction-19]
	_ = x[MemoryKindHostFunction-20]
	_ = x[MemoryKindBoundFunction-21]
	_ = x[MemoryKindBigInt-22]
	_ = x[MemoryKindRawString-23]
	_ = x[MemoryKindVariable-24]
	_ = x[MemoryKindTokenIdentifier-25]
	_ = x[MemoryKindTokenComment-26]
	_ = x[MemoryKindTokenNumericLiteral-27]
	_ = x[MemoryKindTokenSyntax-28]
	_ = x[MemoryKindProgram-29]
	_ = x[MemoryKindIdentifier-30]
	_ = x[MemoryKindArgument-31]
	_ = x[MemoryKindBlock-32]
	_ = x[MemoryKindFunctionBlock-33]
	_ = x[MemoryKindParameter-34]
	_ = x[MemoryKindParameterList-35]
	_ = x[MemoryKindTransfer-36]
	_ = x[MemoryKindMembers-37]
	_ = x[MemoryKindFunctionDeclaration-38]
	_ = x[MemoryKindCompositeDeclaration-39]
	_ = x[MemoryKindInterfaceDeclaration-40]
	_ = x[MemoryKindEnumCaseDeclaration-41]
	_ = x[MemoryKindFieldDeclaration-42]
	_ = x[MemoryKindTransactionDeclaration-43]
	_ = x[MemoryKindImportDeclaration-44]
	_ = x[MemoryKindVariableDeclaration-45]
	_ = x[MemoryKindSpecialFunctionDeclaration-46]
	_ = x[MemoryKindPragmaDeclaration-47]
	_ = x[MemoryKindAssignmentStatement-48]
	_ = x[MemoryKindBreakStatement-49]
	_ = x[MemoryKindContinueStatement-50]
	_ = x[MemoryKindEmitStatement-51]
	_ = x[MemoryKindExpressionStatement-52]
	_ = x[MemoryKindForStatement-53]
	_ = x[MemoryKindIfStatement-54]
	_ = x[MemoryKindReturnStatement-55]
	_ = x[MemoryKindSwapStatement-56]
	_ = x[MemoryKindSwitchStatement-57]
	_ = x[MemoryKindWhileStatement-58]
	_ = x[MemoryKindBooleanExpression-59]
	_ = x[MemoryKindNilExpression-60]
	_ = x[MemoryKindStringExpression-61]
	_ = x[MemoryKindIntegerExpression-62]
	_ = x[MemoryKindFixedPointExpression-63]
	_ = x[MemoryKindArrayExpression-64]
	_ = x[MemoryKindDictionaryExpression-65]
	_ = x[MemoryKindIdentifierExpression-66]
	_ = x[MemoryKindInvocationExpression-67]
	_ = x[MemoryKindMemberExpression-68]
	_ = x[MemoryKindIndexExpression-69]
	_ = x[MemoryKindConditionalExpression-70]
	_ = x[MemoryKindUnaryExpression-71]
	_ = x[MemoryKindBinaryExpression-72]
	_ = x[MemoryKindFunctionExpression-73]
	_ = x[MemoryKindCastingExpression-74]
	_ = x[MemoryKindCreateExpression-75]
	_ = x[MemoryKindDestroyExpression-76]
	_ = x[MemoryKindReferenceExpression-77]
	_ = x[MemoryKindForceExpression-78]
	_ = x[MemoryKindPathExpression-79]
}

const _MemoryKind_name = "UnknownBoolAddressStringCharacterMetaTypeNumberArrayDictionaryCompositeOptionalNilVoidTypeValuePathValueCapabilityValueLinkValueStorageReferenceValueEphemeralReferenceValueInterpretedFunctionHostFunctionBoundFunctionBigIntRawStringVariableTokenIdentifierTokenCommentTokenNumericLiteralTokenSyntaxProgramIdentifierArgumentBlockFunctionBlockParameterParameterListTransferMembersFunctionDeclarationCompositeDeclarationInterfaceDeclarationEnumCaseDeclarationFieldDeclarationTransactionDeclarationImportDeclarationVariableDeclarationSpecialFunctionDeclarationPragmaDeclarationAssignmentStatementBreakStatementContinueStatementEmitStatementExpressionStatementForStatementIfStatementReturnStatementSwapStatementSwitchStatementWhileStatementBooleanExpressionNilExpressionStringExpressionIntegerExpressionFixedPointExpressionArrayExpressionDictionaryExpressionIdentifierExpressionInvocationExpressionMemberExpressionIndexExpressionConditionalExpressionUnaryExpressionBinaryExpressionFunctionExpressionCastingExpressionCreateExpressionDestroyExpressionReferenceExpressionForceExpressionPathExpression"

var _MemoryKind_index = [...]uint16{0, 7, 11, 18, 24, 33, 41, 47, 52, 62, 71, 79, 82, 86, 95, 104, 119, 128, 149, 172, 191, 203, 216, 222, 231, 239, 254, 266, 285, 296, 303, 313, 321, 326, 339, 348, 361, 369, 376, 395, 415, 435, 454, 470, 492, 509, 528, 554, 571, 590, 604, 621, 634, 653, 665, 676, 691, 704, 719, 733, 750, 763, 779, 796, 816, 831, 851, 871, 891, 907, 922, 943, 958, 974, 992, 1009, 1025, 1042, 1061, 1076, 1090}

func (i MemoryKind) String() string {
	if i >= MemoryKind(len(_MemoryKind_index)-1) {
		return "MemoryKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MemoryKind_name[_MemoryKind_index[i]:_MemoryKind_index[i+1]]
}
