/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=OperandSide"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperandSideUnknown-0]
	_ = x[OperandSideLeft-1]
	_ = x[OperandSideRight-2]
}

const _OperandSide_name = "OperandSideUnknownOperandSideLeftOperandSideRight"

var _OperandSide_index = [...]uint8{0, 18, 33, 49}

func (i OperandSide) String() string {
	if i < 0 || i >= OperandSide(len(_OperandSide_index)-1) {
		return "OperandSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperandSide_name[_OperandSide_index[i]:_OperandSide_index[i+1]]
}
