/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=PathDomain"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathDomainUnknown-0]
	_ = x[PathDomainStorage-1]
	_ = x[PathDomainPrivate-2]
	_ = x[PathDomainPublic-3]
}

const _PathDomain_name = "PathDomainUnknownPathDomainStoragePathDomainPrivatePathDomainPublic"

var _PathDomain_index = [...]uint8{0, 17, 34, 51, 67}

func (i PathDomain) String() string {
	if i < 0 || i >= PathDomain(len(_PathDomain_index)-1) {
		return "PathDomain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathDomain_name[_PathDomain_index[i]:_PathDomain_index[i+1]]
}
