// Code generated by "stringer -type=InvalidIntegerLiteralKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidIntegerLiteralKindUnknown-0]
	_ = x[InvalidIntegerLiteralKindLeadingUnderscore-1]
	_ = x[InvalidIntegerLiteralKindTrailingUnderscore-2]
	_ = x[InvalidIntegerLiteralKindUnknownPrefix-3]
}

const _InvalidIntegerLiteralKind_name = "InvalidIntegerLiteralKindUnknownInvalidIntegerLiteralKindLeadingUnderscoreInvalidIntegerLiteralKindTrailingUnderscoreInvalidIntegerLiteralKindUnknownPrefix"

var _InvalidIntegerLiteralKind_index = [...]uint8{0, 32, 74, 117, 155}

func (i InvalidIntegerLiteralKind) String() string {
	if i < 0 || i >= InvalidIntegerLiteralKind(len(_InvalidIntegerLiteralKind_index)-1) {
		return "InvalidIntegerLiteralKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InvalidIntegerLiteralKind_name[_InvalidIntegerLiteralKind_index[i]:_InvalidIntegerLiteralKind_index[i+1]]
}
