name: Reporting a Problem/Bug
description: Reporting a Problem/Bug
labels: [Bug, Feedback]
assignees: onflow/cadence
body:
  - type: markdown
    attributes:
      value: |
        > **Warning**
        > Do you experience a **crash** in Cadence?
        > Please do **NOT** report a crasher as a bug!
        >
        > Instead, report it as a security issue:
        > https://flow.com/flow-responsible-disclosure
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Please share any details and steps that can reproduce the problem
      placeholder: |
        1. When running a transaction with the following code...
        2. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Example:
          - **Cadence version**: v0.31.2
          - **Network**: Emulator
      value: |
        - Cadence version:
        - Network:
      render: markdown
    validations:
      required: true
