// Code generated by gen/main.go from bbq/opcode/instructions.yml. DO NOT EDIT.

package opcode

func (i Opcode) IsControlFlow() bool {
	switch i {
	case Invoke, InvokeTyped, Jump, JumpIfFalse, JumpIfTrue, JumpIfNil, Return, ReturnValue:
		return true
	default:
		return false
	}
}
