// Code generated by "stringer -type=ElementType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElementTypeUnknown-0]
	_ = x[ElementTypeProgram-1]
	_ = x[ElementTypeBlock-2]
	_ = x[ElementTypeFunctionBlock-3]
	_ = x[ElementTypeFunctionDeclaration-4]
	_ = x[ElementTypeSpecialFunctionDeclaration-5]
	_ = x[ElementTypeCompositeDeclaration-6]
	_ = x[ElementTypeInterfaceDeclaration-7]
	_ = x[ElementTypeEntitlementDeclaration-8]
	_ = x[ElementTypeEntitlementMappingDeclaration-9]
	_ = x[ElementTypeAttachmentDeclaration-10]
	_ = x[ElementTypeFieldDeclaration-11]
	_ = x[ElementTypeEnumCaseDeclaration-12]
	_ = x[ElementTypePragmaDeclaration-13]
	_ = x[ElementTypeImportDeclaration-14]
	_ = x[ElementTypeTransactionDeclaration-15]
	_ = x[ElementTypeReturnStatement-16]
	_ = x[ElementTypeBreakStatement-17]
	_ = x[ElementTypeContinueStatement-18]
	_ = x[ElementTypeIfStatement-19]
	_ = x[ElementTypeSwitchStatement-20]
	_ = x[ElementTypeWhileStatement-21]
	_ = x[ElementTypeForStatement-22]
	_ = x[ElementTypeEmitStatement-23]
	_ = x[ElementTypeVariableDeclaration-24]
	_ = x[ElementTypeAssignmentStatement-25]
	_ = x[ElementTypeSwapStatement-26]
	_ = x[ElementTypeExpressionStatement-27]
	_ = x[ElementTypeRemoveStatement-28]
	_ = x[ElementTypeGuardStatement-29]
	_ = x[ElementTypeVoidExpression-30]
	_ = x[ElementTypeBoolExpression-31]
	_ = x[ElementTypeNilExpression-32]
	_ = x[ElementTypeIntegerExpression-33]
	_ = x[ElementTypeFixedPointExpression-34]
	_ = x[ElementTypeArrayExpression-35]
	_ = x[ElementTypeDictionaryExpression-36]
	_ = x[ElementTypeIdentifierExpression-37]
	_ = x[ElementTypeInvocationExpression-38]
	_ = x[ElementTypeMemberExpression-39]
	_ = x[ElementTypeIndexExpression-40]
	_ = x[ElementTypeConditionalExpression-41]
	_ = x[ElementTypeUnaryExpression-42]
	_ = x[ElementTypeBinaryExpression-43]
	_ = x[ElementTypeFunctionExpression-44]
	_ = x[ElementTypeStringExpression-45]
	_ = x[ElementTypeCastingExpression-46]
	_ = x[ElementTypeCreateExpression-47]
	_ = x[ElementTypeDestroyExpression-48]
	_ = x[ElementTypeReferenceExpression-49]
	_ = x[ElementTypeForceExpression-50]
	_ = x[ElementTypePathExpression-51]
	_ = x[ElementTypeAttachExpression-52]
	_ = x[ElementTypeStringTemplateExpression-53]
	_ = x[ElementTypeTypeAnnotation-54]
	_ = x[ElementTypeNominalType-55]
	_ = x[ElementTypeOptionalType-56]
	_ = x[ElementTypeVariableSizedType-57]
	_ = x[ElementTypeConstantSizedType-58]
	_ = x[ElementTypeDictionaryType-59]
	_ = x[ElementTypeFunctionType-60]
	_ = x[ElementTypeReferenceType-61]
	_ = x[ElementTypeIntersectionType-62]
	_ = x[ElementTypeInstantiationType-63]
}

const _ElementType_name = "ElementTypeUnknownElementTypeProgramElementTypeBlockElementTypeFunctionBlockElementTypeFunctionDeclarationElementTypeSpecialFunctionDeclarationElementTypeCompositeDeclarationElementTypeInterfaceDeclarationElementTypeEntitlementDeclarationElementTypeEntitlementMappingDeclarationElementTypeAttachmentDeclarationElementTypeFieldDeclarationElementTypeEnumCaseDeclarationElementTypePragmaDeclarationElementTypeImportDeclarationElementTypeTransactionDeclarationElementTypeReturnStatementElementTypeBreakStatementElementTypeContinueStatementElementTypeIfStatementElementTypeSwitchStatementElementTypeWhileStatementElementTypeForStatementElementTypeEmitStatementElementTypeVariableDeclarationElementTypeAssignmentStatementElementTypeSwapStatementElementTypeExpressionStatementElementTypeRemoveStatementElementTypeGuardStatementElementTypeVoidExpressionElementTypeBoolExpressionElementTypeNilExpressionElementTypeIntegerExpressionElementTypeFixedPointExpressionElementTypeArrayExpressionElementTypeDictionaryExpressionElementTypeIdentifierExpressionElementTypeInvocationExpressionElementTypeMemberExpressionElementTypeIndexExpressionElementTypeConditionalExpressionElementTypeUnaryExpressionElementTypeBinaryExpressionElementTypeFunctionExpressionElementTypeStringExpressionElementTypeCastingExpressionElementTypeCreateExpressionElementTypeDestroyExpressionElementTypeReferenceExpressionElementTypeForceExpressionElementTypePathExpressionElementTypeAttachExpressionElementTypeStringTemplateExpressionElementTypeTypeAnnotationElementTypeNominalTypeElementTypeOptionalTypeElementTypeVariableSizedTypeElementTypeConstantSizedTypeElementTypeDictionaryTypeElementTypeFunctionTypeElementTypeReferenceTypeElementTypeIntersectionTypeElementTypeInstantiationType"

var _ElementType_index = [...]uint16{0, 18, 36, 52, 76, 106, 143, 174, 205, 238, 278, 310, 337, 367, 395, 423, 456, 482, 507, 535, 557, 583, 608, 631, 655, 685, 715, 739, 769, 795, 820, 845, 870, 894, 922, 953, 979, 1010, 1041, 1072, 1099, 1125, 1157, 1183, 1210, 1239, 1266, 1294, 1321, 1349, 1379, 1405, 1430, 1457, 1492, 1517, 1539, 1562, 1590, 1618, 1643, 1666, 1690, 1717, 1745}

func (i ElementType) String() string {
	if i >= ElementType(len(_ElementType_index)-1) {
		return "ElementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElementType_name[_ElementType_index[i]:_ElementType_index[i+1]]
}
