// Code generated by "stringer -type=TransferOperation"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransferOperationUnknown-0]
	_ = x[TransferOperationCopy-1]
	_ = x[TransferOperationMove-2]
	_ = x[TransferOperationMoveForced-3]
	_ = x[TransferOperationInternalNoTransfer-4]
}

const _TransferOperation_name = "TransferOperationUnknownTransferOperationCopyTransferOperationMoveTransferOperationMoveForcedTransferOperationInternalNoTransfer"

var _TransferOperation_index = [...]uint8{0, 24, 45, 66, 93, 128}

func (i TransferOperation) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TransferOperation_index)-1 {
		return "TransferOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferOperation_name[_TransferOperation_index[idx]:_TransferOperation_index[idx+1]]
}
