// Code generated by "stringer -type=TransferOperation"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransferOperationUnknown-0]
	_ = x[TransferOperationCopy-1]
	_ = x[TransferOperationMove-2]
	_ = x[TransferOperationMoveForced-3]
}

const _TransferOperation_name = "TransferOperationUnknownTransferOperationCopyTransferOperationMoveTransferOperationMoveForced"

var _TransferOperation_index = [...]uint8{0, 24, 45, 66, 93}

func (i TransferOperation) String() string {
	if i >= TransferOperation(len(_TransferOperation_index)-1) {
		return "TransferOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferOperation_name[_TransferOperation_index[i]:_TransferOperation_index[i+1]]
}
