// Code generated by "stringer -type=typePrecedence"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[typePrecedenceUnknown-0]
	_ = x[typePrecedenceOptional-1]
	_ = x[typePrecedenceReference-2]
	_ = x[typePrecedenceInstantiation-3]
	_ = x[typePrecedencePrimary-4]
}

const _typePrecedence_name = "typePrecedenceUnknowntypePrecedenceOptionaltypePrecedenceReferencetypePrecedenceInstantiationtypePrecedencePrimary"

var _typePrecedence_index = [...]uint8{0, 21, 43, 66, 93, 114}

func (i typePrecedence) String() string {
	if i >= typePrecedence(len(_typePrecedence_index)-1) {
		return "typePrecedence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _typePrecedence_name[_typePrecedence_index[i]:_typePrecedence_index[i+1]]
}
