// Code generated by "stringer -type=TypePrecedence"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypePrecedenceUnknown-0]
	_ = x[TypePrecedenceOptional-1]
	_ = x[TypePrecedenceReference-2]
	_ = x[TypePrecedenceInstantiation-3]
	_ = x[TypePrecedencePrimary-4]
}

const _TypePrecedence_name = "TypePrecedenceUnknownTypePrecedenceOptionalTypePrecedenceReferenceTypePrecedenceInstantiationTypePrecedencePrimary"

var _TypePrecedence_index = [...]uint8{0, 21, 43, 66, 93, 114}

func (i TypePrecedence) String() string {
	if i >= TypePrecedence(len(_TypePrecedence_index)-1) {
		return "TypePrecedence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypePrecedence_name[_TypePrecedence_index[i]:_TypePrecedence_index[i+1]]
}
