// Code generated by "stringer -type=VariableKind"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VariableKindNotSpecified-0]
	_ = x[VariableKindVariable-1]
	_ = x[VariableKindConstant-2]
}

const _VariableKind_name = "VariableKindNotSpecifiedVariableKindVariableVariableKindConstant"

var _VariableKind_index = [...]uint8{0, 24, 44, 64}

func (i VariableKind) String() string {
	if i >= VariableKind(len(_VariableKind_index)-1) {
		return "VariableKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariableKind_name[_VariableKind_index[i]:_VariableKind_index[i+1]]
}
