package parser2

const (
	keywordIf          = "if"
	keywordElse        = "else"
	keywordWhile       = "while"
	keywordBreak       = "break"
	keywordContinue    = "continue"
	keywordReturn      = "return"
	keywordTrue        = "true"
	keywordFalse       = "false"
	keywordNil         = "nil"
	keywordLet         = "let"
	keywordVar         = "var"
	keywordFun         = "fun"
	keywordAs          = "as"
	keywordCreate      = "create"
	keywordDestroy     = "destroy"
	keywordFor         = "for"
	keywordIn          = "in"
	keywordEmit        = "emit"
	keywordAuth        = "auth"
	keywordPriv        = "priv"
	keywordPub         = "pub"
	keywordAccess      = "access"
	keywordSet         = "set"
	keywordAll         = "all"
	keywordSelf        = "self"
	keywordInit        = "init"
	keywordContract    = "contract"
	keywordAccount     = "account"
	keywordImport      = "import"
	keywordFrom        = "from"
	keywordPre         = "pre"
	keywordPost        = "post"
	keywordEvent       = "event"
	keywordStruct      = "struct"
	keywordResource    = "resource"
	keywordInterface   = "interface"
	keywordTransaction = "transaction"
	keywordPrepare     = "prepare"
	keywordExecute     = "execute"
)
