// Code generated by "stringer -type=ControlStatement"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControlStatementUnknown-0]
	_ = x[ControlStatementBreak-1]
	_ = x[ControlStatementContinue-2]
}

const _ControlStatement_name = "ControlStatementUnknownControlStatementBreakControlStatementContinue"

var _ControlStatement_index = [...]uint8{0, 23, 44, 68}

func (i ControlStatement) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ControlStatement_index)-1 {
		return "ControlStatement(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControlStatement_name[_ControlStatement_index[idx]:_ControlStatement_index[idx+1]]
}
