// Code generated by "stringer -type=IntegerLiteralKind"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntegerLiteralKindUnknown-0]
	_ = x[IntegerLiteralKindBinary-1]
	_ = x[IntegerLiteralKindOctal-2]
	_ = x[IntegerLiteralKindDecimal-3]
	_ = x[IntegerLiteralKindHexadecimal-4]
}

const _IntegerLiteralKind_name = "IntegerLiteralKindUnknownIntegerLiteralKindBinaryIntegerLiteralKindOctalIntegerLiteralKindDecimalIntegerLiteralKindHexadecimal"

var _IntegerLiteralKind_index = [...]uint8{0, 25, 49, 72, 97, 126}

func (i IntegerLiteralKind) String() string {
	if i >= IntegerLiteralKind(len(_IntegerLiteralKind_index)-1) {
		return "IntegerLiteralKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IntegerLiteralKind_name[_IntegerLiteralKind_index[i]:_IntegerLiteralKind_index[i+1]]
}
