// Code generated by "stringer -type=PathDomain"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathDomainUnknown-0]
	_ = x[PathDomainStorage-1]
	_ = x[PathDomainPrivate-2]
	_ = x[PathDomainPublic-3]
}

const _PathDomain_name = "PathDomainUnknownPathDomainStoragePathDomainPrivatePathDomainPublic"

var _PathDomain_index = [...]uint8{0, 17, 34, 51, 67}

func (i PathDomain) String() string {
	if i >= PathDomain(len(_PathDomain_index)-1) {
		return "PathDomain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathDomain_name[_PathDomain_index[i]:_PathDomain_index[i+1]]
}
