// Code generated by "stringer -type=BinOp"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinOpUnknown-0]
	_ = x[BinOpPlus-1]
}

const _BinOp_name = "BinOpUnknownBinOpPlus"

var _BinOp_index = [...]uint8{0, 12, 21}

func (i BinOp) String() string {
	if i >= BinOp(len(_BinOp_index)-1) {
		return "BinOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinOp_name[_BinOp_index[i]:_BinOp_index[i+1]]
}
