// Code generated by "stringer -type=ValType"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValTypeUnknown-0]
	_ = x[ValTypeInt-1]
	_ = x[ValTypeString-2]
}

const _ValType_name = "ValTypeUnknownValTypeIntValTypeString"

var _ValType_index = [...]uint8{0, 14, 24, 37}

func (i ValType) String() string {
	if i >= ValType(len(_ValType_index)-1) {
		return "ValType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValType_name[_ValType_index[i]:_ValType_index[i+1]]
}
