// Code generated by "stringer -type=HashInputType -trimprefix=HashInputType"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashInputTypeBool-0]
	_ = x[HashInputTypeString-1]
	_ = x[HashInputTypeEnum-2]
	_ = x[HashInputTypeAddress-3]
	_ = x[HashInputTypePath-4]
	_ = x[HashInputTypeType-5]
	_ = x[HashInputTypeCharacter-6]
	_ = x[HashInputTypeInt-10]
	_ = x[HashInputTypeInt8-11]
	_ = x[HashInputTypeInt16-12]
	_ = x[HashInputTypeInt32-13]
	_ = x[HashInputTypeInt64-14]
	_ = x[HashInputTypeInt128-15]
	_ = x[HashInputTypeInt256-16]
	_ = x[HashInputTypeUInt-18]
	_ = x[HashInputTypeUInt8-19]
	_ = x[HashInputTypeUInt16-20]
	_ = x[HashInputTypeUInt32-21]
	_ = x[HashInputTypeUInt64-22]
	_ = x[HashInputTypeUInt128-23]
	_ = x[HashInputTypeUInt256-24]
	_ = x[HashInputTypeWord8-27]
	_ = x[HashInputTypeWord16-28]
	_ = x[HashInputTypeWord32-29]
	_ = x[HashInputTypeWord64-30]
	_ = x[HashInputTypeWord128-31]
	_ = x[HashInputTypeWord256-32]
	_ = x[HashInputTypeFix64-38]
	_ = x[HashInputTypeFix128-39]
	_ = x[HashInputTypeUFix64-46]
	_ = x[HashInputTypeUFix128-47]
	_ = x[HashInputType_Count-50]
}

const (
	_HashInputType_name_0 = "BoolStringEnumAddressPathTypeCharacter"
	_HashInputType_name_1 = "IntInt8Int16Int32Int64Int128Int256"
	_HashInputType_name_2 = "UIntUInt8UInt16UInt32UInt64UInt128UInt256"
	_HashInputType_name_3 = "Word8Word16Word32Word64Word128Word256"
	_HashInputType_name_4 = "Fix64Fix128"
	_HashInputType_name_5 = "UFix64UFix128"
	_HashInputType_name_6 = "_Count"
)

var (
	_HashInputType_index_0 = [...]uint8{0, 4, 10, 14, 21, 25, 29, 38}
	_HashInputType_index_1 = [...]uint8{0, 3, 7, 12, 17, 22, 28, 34}
	_HashInputType_index_2 = [...]uint8{0, 4, 9, 15, 21, 27, 34, 41}
	_HashInputType_index_3 = [...]uint8{0, 5, 11, 17, 23, 30, 37}
	_HashInputType_index_4 = [...]uint8{0, 5, 11}
	_HashInputType_index_5 = [...]uint8{0, 6, 13}
)

func (i HashInputType) String() string {
	switch {
	case i <= 6:
		return _HashInputType_name_0[_HashInputType_index_0[i]:_HashInputType_index_0[i+1]]
	case 10 <= i && i <= 16:
		i -= 10
		return _HashInputType_name_1[_HashInputType_index_1[i]:_HashInputType_index_1[i+1]]
	case 18 <= i && i <= 24:
		i -= 18
		return _HashInputType_name_2[_HashInputType_index_2[i]:_HashInputType_index_2[i+1]]
	case 27 <= i && i <= 32:
		i -= 27
		return _HashInputType_name_3[_HashInputType_index_3[i]:_HashInputType_index_3[i+1]]
	case 38 <= i && i <= 39:
		i -= 38
		return _HashInputType_name_4[_HashInputType_index_4[i]:_HashInputType_index_4[i+1]]
	case 46 <= i && i <= 47:
		i -= 46
		return _HashInputType_name_5[_HashInputType_index_5[i]:_HashInputType_index_5[i+1]]
	case i == 50:
		return _HashInputType_name_6
	default:
		return "HashInputType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
