// Code generated by "stringer -type=PrimitiveStaticType -trimprefix=PrimitiveStaticType"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimitiveStaticTypeUnknown-0]
	_ = x[PrimitiveStaticTypeVoid-1]
	_ = x[PrimitiveStaticTypeAny-2]
	_ = x[PrimitiveStaticTypeNever-3]
	_ = x[PrimitiveStaticTypeAnyStruct-4]
	_ = x[PrimitiveStaticTypeAnyResource-5]
	_ = x[PrimitiveStaticTypeBool-6]
	_ = x[PrimitiveStaticTypeAddress-7]
	_ = x[PrimitiveStaticTypeString-8]
	_ = x[PrimitiveStaticTypeCharacter-9]
	_ = x[PrimitiveStaticTypeMetaType-10]
	_ = x[PrimitiveStaticTypeBlock-11]
	_ = x[PrimitiveStaticTypeAnyResourceAttachment-12]
	_ = x[PrimitiveStaticTypeAnyStructAttachment-13]
	_ = x[PrimitiveStaticTypeHashableStruct-14]
	_ = x[PrimitiveStaticTypeStorable-15]
	_ = x[PrimitiveStaticTypeNumber-18]
	_ = x[PrimitiveStaticTypeSignedNumber-19]
	_ = x[PrimitiveStaticTypeInteger-24]
	_ = x[PrimitiveStaticTypeSignedInteger-25]
	_ = x[PrimitiveStaticTypeFixedSizeUnsignedInteger-26]
	_ = x[PrimitiveStaticTypeFixedPoint-30]
	_ = x[PrimitiveStaticTypeSignedFixedPoint-31]
	_ = x[PrimitiveStaticTypeInt-36]
	_ = x[PrimitiveStaticTypeInt8-37]
	_ = x[PrimitiveStaticTypeInt16-38]
	_ = x[PrimitiveStaticTypeInt32-39]
	_ = x[PrimitiveStaticTypeInt64-40]
	_ = x[PrimitiveStaticTypeInt128-41]
	_ = x[PrimitiveStaticTypeInt256-42]
	_ = x[PrimitiveStaticTypeUInt-44]
	_ = x[PrimitiveStaticTypeUInt8-45]
	_ = x[PrimitiveStaticTypeUInt16-46]
	_ = x[PrimitiveStaticTypeUInt32-47]
	_ = x[PrimitiveStaticTypeUInt64-48]
	_ = x[PrimitiveStaticTypeUInt128-49]
	_ = x[PrimitiveStaticTypeUInt256-50]
	_ = x[PrimitiveStaticTypeWord8-53]
	_ = x[PrimitiveStaticTypeWord16-54]
	_ = x[PrimitiveStaticTypeWord32-55]
	_ = x[PrimitiveStaticTypeWord64-56]
	_ = x[PrimitiveStaticTypeWord128-57]
	_ = x[PrimitiveStaticTypeWord256-58]
	_ = x[PrimitiveStaticTypeFix64-64]
	_ = x[PrimitiveStaticTypeFix128-65]
	_ = x[PrimitiveStaticTypeUFix64-72]
	_ = x[PrimitiveStaticTypeUFix128-73]
	_ = x[PrimitiveStaticTypePath-76]
	_ = x[PrimitiveStaticTypeCapability-77]
	_ = x[PrimitiveStaticTypeStoragePath-78]
	_ = x[PrimitiveStaticTypeCapabilityPath-79]
	_ = x[PrimitiveStaticTypePublicPath-80]
	_ = x[PrimitiveStaticTypePrivatePath-81]
	_ = x[PrimitiveStaticTypeAuthAccount-90]
	_ = x[PrimitiveStaticTypePublicAccount-91]
	_ = x[PrimitiveStaticTypeDeployedContract-92]
	_ = x[PrimitiveStaticTypeAuthAccountContracts-93]
	_ = x[PrimitiveStaticTypePublicAccountContracts-94]
	_ = x[PrimitiveStaticTypeAuthAccountKeys-95]
	_ = x[PrimitiveStaticTypePublicAccountKeys-96]
	_ = x[PrimitiveStaticTypeAccountKey-97]
	_ = x[PrimitiveStaticTypeAuthAccountInbox-98]
	_ = x[PrimitiveStaticTypeStorageCapabilityController-99]
	_ = x[PrimitiveStaticTypeAccountCapabilityController-100]
	_ = x[PrimitiveStaticTypeAuthAccountStorageCapabilities-101]
	_ = x[PrimitiveStaticTypeAuthAccountAccountCapabilities-102]
	_ = x[PrimitiveStaticTypeAuthAccountCapabilities-103]
	_ = x[PrimitiveStaticTypePublicAccountCapabilities-104]
	_ = x[PrimitiveStaticTypeAccount-105]
	_ = x[PrimitiveStaticTypeAccount_Contracts-106]
	_ = x[PrimitiveStaticTypeAccount_Keys-107]
	_ = x[PrimitiveStaticTypeAccount_Inbox-108]
	_ = x[PrimitiveStaticTypeAccount_StorageCapabilities-109]
	_ = x[PrimitiveStaticTypeAccount_AccountCapabilities-110]
	_ = x[PrimitiveStaticTypeAccount_Capabilities-111]
	_ = x[PrimitiveStaticTypeAccount_Storage-112]
	_ = x[PrimitiveStaticTypeMutate-118]
	_ = x[PrimitiveStaticTypeInsert-119]
	_ = x[PrimitiveStaticTypeRemove-120]
	_ = x[PrimitiveStaticTypeIdentity-121]
	_ = x[PrimitiveStaticTypeStorage-125]
	_ = x[PrimitiveStaticTypeSaveValue-126]
	_ = x[PrimitiveStaticTypeLoadValue-127]
	_ = x[PrimitiveStaticTypeCopyValue-128]
	_ = x[PrimitiveStaticTypeBorrowValue-129]
	_ = x[PrimitiveStaticTypeContracts-130]
	_ = x[PrimitiveStaticTypeAddContract-131]
	_ = x[PrimitiveStaticTypeUpdateContract-132]
	_ = x[PrimitiveStaticTypeRemoveContract-133]
	_ = x[PrimitiveStaticTypeKeys-134]
	_ = x[PrimitiveStaticTypeAddKey-135]
	_ = x[PrimitiveStaticTypeRevokeKey-136]
	_ = x[PrimitiveStaticTypeInbox-137]
	_ = x[PrimitiveStaticTypePublishInboxCapability-138]
	_ = x[PrimitiveStaticTypeUnpublishInboxCapability-139]
	_ = x[PrimitiveStaticTypeClaimInboxCapability-140]
	_ = x[PrimitiveStaticTypeCapabilities-141]
	_ = x[PrimitiveStaticTypeStorageCapabilities-142]
	_ = x[PrimitiveStaticTypeAccountCapabilities-143]
	_ = x[PrimitiveStaticTypePublishCapability-144]
	_ = x[PrimitiveStaticTypeUnpublishCapability-145]
	_ = x[PrimitiveStaticTypeGetStorageCapabilityController-146]
	_ = x[PrimitiveStaticTypeIssueStorageCapabilityController-147]
	_ = x[PrimitiveStaticTypeGetAccountCapabilityController-148]
	_ = x[PrimitiveStaticTypeIssueAccountCapabilityController-149]
	_ = x[PrimitiveStaticTypeCapabilitiesMapping-150]
	_ = x[PrimitiveStaticTypeAccountMapping-151]
	_ = x[PrimitiveStaticType_Count-152]
}

const _PrimitiveStaticType_name = "UnknownVoidAnyNeverAnyStructAnyResourceBoolAddressStringCharacterMetaTypeBlockAnyResourceAttachmentAnyStructAttachmentHashableStructStorableNumberSignedNumberIntegerSignedIntegerFixedSizeUnsignedIntegerFixedPointSignedFixedPointIntInt8Int16Int32Int64Int128Int256UIntUInt8UInt16UInt32UInt64UInt128UInt256Word8Word16Word32Word64Word128Word256Fix64Fix128UFix64UFix128PathCapabilityStoragePathCapabilityPathPublicPathPrivatePathAuthAccountPublicAccountDeployedContractAuthAccountContractsPublicAccountContractsAuthAccountKeysPublicAccountKeysAccountKeyAuthAccountInboxStorageCapabilityControllerAccountCapabilityControllerAuthAccountStorageCapabilitiesAuthAccountAccountCapabilitiesAuthAccountCapabilitiesPublicAccountCapabilitiesAccountAccount_ContractsAccount_KeysAccount_InboxAccount_StorageCapabilitiesAccount_AccountCapabilitiesAccount_CapabilitiesAccount_StorageMutateInsertRemoveIdentityStorageSaveValueLoadValueCopyValueBorrowValueContractsAddContractUpdateContractRemoveContractKeysAddKeyRevokeKeyInboxPublishInboxCapabilityUnpublishInboxCapabilityClaimInboxCapabilityCapabilitiesStorageCapabilitiesAccountCapabilitiesPublishCapabilityUnpublishCapabilityGetStorageCapabilityControllerIssueStorageCapabilityControllerGetAccountCapabilityControllerIssueAccountCapabilityControllerCapabilitiesMappingAccountMapping_Count"

var _PrimitiveStaticType_map = map[PrimitiveStaticType]string{
	0:   _PrimitiveStaticType_name[0:7],
	1:   _PrimitiveStaticType_name[7:11],
	2:   _PrimitiveStaticType_name[11:14],
	3:   _PrimitiveStaticType_name[14:19],
	4:   _PrimitiveStaticType_name[19:28],
	5:   _PrimitiveStaticType_name[28:39],
	6:   _PrimitiveStaticType_name[39:43],
	7:   _PrimitiveStaticType_name[43:50],
	8:   _PrimitiveStaticType_name[50:56],
	9:   _PrimitiveStaticType_name[56:65],
	10:  _PrimitiveStaticType_name[65:73],
	11:  _PrimitiveStaticType_name[73:78],
	12:  _PrimitiveStaticType_name[78:99],
	13:  _PrimitiveStaticType_name[99:118],
	14:  _PrimitiveStaticType_name[118:132],
	15:  _PrimitiveStaticType_name[132:140],
	18:  _PrimitiveStaticType_name[140:146],
	19:  _PrimitiveStaticType_name[146:158],
	24:  _PrimitiveStaticType_name[158:165],
	25:  _PrimitiveStaticType_name[165:178],
	26:  _PrimitiveStaticType_name[178:202],
	30:  _PrimitiveStaticType_name[202:212],
	31:  _PrimitiveStaticType_name[212:228],
	36:  _PrimitiveStaticType_name[228:231],
	37:  _PrimitiveStaticType_name[231:235],
	38:  _PrimitiveStaticType_name[235:240],
	39:  _PrimitiveStaticType_name[240:245],
	40:  _PrimitiveStaticType_name[245:250],
	41:  _PrimitiveStaticType_name[250:256],
	42:  _PrimitiveStaticType_name[256:262],
	44:  _PrimitiveStaticType_name[262:266],
	45:  _PrimitiveStaticType_name[266:271],
	46:  _PrimitiveStaticType_name[271:277],
	47:  _PrimitiveStaticType_name[277:283],
	48:  _PrimitiveStaticType_name[283:289],
	49:  _PrimitiveStaticType_name[289:296],
	50:  _PrimitiveStaticType_name[296:303],
	53:  _PrimitiveStaticType_name[303:308],
	54:  _PrimitiveStaticType_name[308:314],
	55:  _PrimitiveStaticType_name[314:320],
	56:  _PrimitiveStaticType_name[320:326],
	57:  _PrimitiveStaticType_name[326:333],
	58:  _PrimitiveStaticType_name[333:340],
	64:  _PrimitiveStaticType_name[340:345],
	65:  _PrimitiveStaticType_name[345:351],
	72:  _PrimitiveStaticType_name[351:357],
	73:  _PrimitiveStaticType_name[357:364],
	76:  _PrimitiveStaticType_name[364:368],
	77:  _PrimitiveStaticType_name[368:378],
	78:  _PrimitiveStaticType_name[378:389],
	79:  _PrimitiveStaticType_name[389:403],
	80:  _PrimitiveStaticType_name[403:413],
	81:  _PrimitiveStaticType_name[413:424],
	90:  _PrimitiveStaticType_name[424:435],
	91:  _PrimitiveStaticType_name[435:448],
	92:  _PrimitiveStaticType_name[448:464],
	93:  _PrimitiveStaticType_name[464:484],
	94:  _PrimitiveStaticType_name[484:506],
	95:  _PrimitiveStaticType_name[506:521],
	96:  _PrimitiveStaticType_name[521:538],
	97:  _PrimitiveStaticType_name[538:548],
	98:  _PrimitiveStaticType_name[548:564],
	99:  _PrimitiveStaticType_name[564:591],
	100: _PrimitiveStaticType_name[591:618],
	101: _PrimitiveStaticType_name[618:648],
	102: _PrimitiveStaticType_name[648:678],
	103: _PrimitiveStaticType_name[678:701],
	104: _PrimitiveStaticType_name[701:726],
	105: _PrimitiveStaticType_name[726:733],
	106: _PrimitiveStaticType_name[733:750],
	107: _PrimitiveStaticType_name[750:762],
	108: _PrimitiveStaticType_name[762:775],
	109: _PrimitiveStaticType_name[775:802],
	110: _PrimitiveStaticType_name[802:829],
	111: _PrimitiveStaticType_name[829:849],
	112: _PrimitiveStaticType_name[849:864],
	118: _PrimitiveStaticType_name[864:870],
	119: _PrimitiveStaticType_name[870:876],
	120: _PrimitiveStaticType_name[876:882],
	121: _PrimitiveStaticType_name[882:890],
	125: _PrimitiveStaticType_name[890:897],
	126: _PrimitiveStaticType_name[897:906],
	127: _PrimitiveStaticType_name[906:915],
	128: _PrimitiveStaticType_name[915:924],
	129: _PrimitiveStaticType_name[924:935],
	130: _PrimitiveStaticType_name[935:944],
	131: _PrimitiveStaticType_name[944:955],
	132: _PrimitiveStaticType_name[955:969],
	133: _PrimitiveStaticType_name[969:983],
	134: _PrimitiveStaticType_name[983:987],
	135: _PrimitiveStaticType_name[987:993],
	136: _PrimitiveStaticType_name[993:1002],
	137: _PrimitiveStaticType_name[1002:1007],
	138: _PrimitiveStaticType_name[1007:1029],
	139: _PrimitiveStaticType_name[1029:1053],
	140: _PrimitiveStaticType_name[1053:1073],
	141: _PrimitiveStaticType_name[1073:1085],
	142: _PrimitiveStaticType_name[1085:1104],
	143: _PrimitiveStaticType_name[1104:1123],
	144: _PrimitiveStaticType_name[1123:1140],
	145: _PrimitiveStaticType_name[1140:1159],
	146: _PrimitiveStaticType_name[1159:1189],
	147: _PrimitiveStaticType_name[1189:1221],
	148: _PrimitiveStaticType_name[1221:1251],
	149: _PrimitiveStaticType_name[1251:1283],
	150: _PrimitiveStaticType_name[1283:1302],
	151: _PrimitiveStaticType_name[1302:1316],
	152: _PrimitiveStaticType_name[1316:1322],
}

func (i PrimitiveStaticType) String() string {
	if str, ok := _PrimitiveStaticType_map[i]; ok {
		return str
	}
	return "PrimitiveStaticType(" + strconv.FormatInt(int64(i), 10) + ")"
}
