// Code generated by "stringer -type=PrimitiveStaticType -trimprefix=PrimitiveStaticType"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimitiveStaticTypeUnknown-0]
	_ = x[PrimitiveStaticTypeVoid-1]
	_ = x[PrimitiveStaticTypeAny-2]
	_ = x[PrimitiveStaticTypeNever-3]
	_ = x[PrimitiveStaticTypeAnyStruct-4]
	_ = x[PrimitiveStaticTypeAnyResource-5]
	_ = x[PrimitiveStaticTypeBool-6]
	_ = x[PrimitiveStaticTypeAddress-7]
	_ = x[PrimitiveStaticTypeString-8]
	_ = x[PrimitiveStaticTypeCharacter-9]
	_ = x[PrimitiveStaticTypeMetaType-10]
	_ = x[PrimitiveStaticTypeBlock-11]
	_ = x[PrimitiveStaticTypeAnyResourceAttachment-12]
	_ = x[PrimitiveStaticTypeAnyStructAttachment-13]
	_ = x[PrimitiveStaticTypeHashableStruct-14]
	_ = x[PrimitiveStaticTypeStorable-15]
	_ = x[PrimitiveStaticTypeInvalid-16]
	_ = x[PrimitiveStaticTypeNumber-18]
	_ = x[PrimitiveStaticTypeSignedNumber-19]
	_ = x[PrimitiveStaticTypeInteger-24]
	_ = x[PrimitiveStaticTypeSignedInteger-25]
	_ = x[PrimitiveStaticTypeFixedSizeUnsignedInteger-26]
	_ = x[PrimitiveStaticTypeFixedPoint-30]
	_ = x[PrimitiveStaticTypeSignedFixedPoint-31]
	_ = x[PrimitiveStaticTypeInt-36]
	_ = x[PrimitiveStaticTypeInt8-37]
	_ = x[PrimitiveStaticTypeInt16-38]
	_ = x[PrimitiveStaticTypeInt32-39]
	_ = x[PrimitiveStaticTypeInt64-40]
	_ = x[PrimitiveStaticTypeInt128-41]
	_ = x[PrimitiveStaticTypeInt256-42]
	_ = x[PrimitiveStaticTypeUInt-44]
	_ = x[PrimitiveStaticTypeUInt8-45]
	_ = x[PrimitiveStaticTypeUInt16-46]
	_ = x[PrimitiveStaticTypeUInt32-47]
	_ = x[PrimitiveStaticTypeUInt64-48]
	_ = x[PrimitiveStaticTypeUInt128-49]
	_ = x[PrimitiveStaticTypeUInt256-50]
	_ = x[PrimitiveStaticTypeWord8-53]
	_ = x[PrimitiveStaticTypeWord16-54]
	_ = x[PrimitiveStaticTypeWord32-55]
	_ = x[PrimitiveStaticTypeWord64-56]
	_ = x[PrimitiveStaticTypeWord128-57]
	_ = x[PrimitiveStaticTypeWord256-58]
	_ = x[PrimitiveStaticTypeFix64-64]
	_ = x[PrimitiveStaticTypeFix128-65]
	_ = x[PrimitiveStaticTypeUFix64-72]
	_ = x[PrimitiveStaticTypeUFix128-73]
	_ = x[PrimitiveStaticTypePath-76]
	_ = x[PrimitiveStaticTypeCapability-77]
	_ = x[PrimitiveStaticTypeStoragePath-78]
	_ = x[PrimitiveStaticTypeCapabilityPath-79]
	_ = x[PrimitiveStaticTypePublicPath-80]
	_ = x[PrimitiveStaticTypePrivatePath-81]
	_ = x[PrimitiveStaticTypeAuthAccount-90]
	_ = x[PrimitiveStaticTypePublicAccount-91]
	_ = x[PrimitiveStaticTypeDeployedContract-92]
	_ = x[PrimitiveStaticTypeAuthAccountContracts-93]
	_ = x[PrimitiveStaticTypePublicAccountContracts-94]
	_ = x[PrimitiveStaticTypeAuthAccountKeys-95]
	_ = x[PrimitiveStaticTypePublicAccountKeys-96]
	_ = x[PrimitiveStaticTypeAccountKey-97]
	_ = x[PrimitiveStaticTypeAuthAccountInbox-98]
	_ = x[PrimitiveStaticTypeStorageCapabilityController-99]
	_ = x[PrimitiveStaticTypeAccountCapabilityController-100]
	_ = x[PrimitiveStaticTypeAuthAccountStorageCapabilities-101]
	_ = x[PrimitiveStaticTypeAuthAccountAccountCapabilities-102]
	_ = x[PrimitiveStaticTypeAuthAccountCapabilities-103]
	_ = x[PrimitiveStaticTypePublicAccountCapabilities-104]
	_ = x[PrimitiveStaticTypeAccount-105]
	_ = x[PrimitiveStaticTypeAccount_Contracts-106]
	_ = x[PrimitiveStaticTypeAccount_Keys-107]
	_ = x[PrimitiveStaticTypeAccount_Inbox-108]
	_ = x[PrimitiveStaticTypeAccount_StorageCapabilities-109]
	_ = x[PrimitiveStaticTypeAccount_AccountCapabilities-110]
	_ = x[PrimitiveStaticTypeAccount_Capabilities-111]
	_ = x[PrimitiveStaticTypeAccount_Storage-112]
	_ = x[PrimitiveStaticTypeMutate-118]
	_ = x[PrimitiveStaticTypeInsert-119]
	_ = x[PrimitiveStaticTypeRemove-120]
	_ = x[PrimitiveStaticTypeIdentity-121]
	_ = x[PrimitiveStaticTypeStorage-125]
	_ = x[PrimitiveStaticTypeSaveValue-126]
	_ = x[PrimitiveStaticTypeLoadValue-127]
	_ = x[PrimitiveStaticTypeCopyValue-128]
	_ = x[PrimitiveStaticTypeBorrowValue-129]
	_ = x[PrimitiveStaticTypeContracts-130]
	_ = x[PrimitiveStaticTypeAddContract-131]
	_ = x[PrimitiveStaticTypeUpdateContract-132]
	_ = x[PrimitiveStaticTypeRemoveContract-133]
	_ = x[PrimitiveStaticTypeKeys-134]
	_ = x[PrimitiveStaticTypeAddKey-135]
	_ = x[PrimitiveStaticTypeRevokeKey-136]
	_ = x[PrimitiveStaticTypeInbox-137]
	_ = x[PrimitiveStaticTypePublishInboxCapability-138]
	_ = x[PrimitiveStaticTypeUnpublishInboxCapability-139]
	_ = x[PrimitiveStaticTypeClaimInboxCapability-140]
	_ = x[PrimitiveStaticTypeCapabilities-141]
	_ = x[PrimitiveStaticTypeStorageCapabilities-142]
	_ = x[PrimitiveStaticTypeAccountCapabilities-143]
	_ = x[PrimitiveStaticTypePublishCapability-144]
	_ = x[PrimitiveStaticTypeUnpublishCapability-145]
	_ = x[PrimitiveStaticTypeGetStorageCapabilityController-146]
	_ = x[PrimitiveStaticTypeIssueStorageCapabilityController-147]
	_ = x[PrimitiveStaticTypeGetAccountCapabilityController-148]
	_ = x[PrimitiveStaticTypeIssueAccountCapabilityController-149]
	_ = x[PrimitiveStaticTypeCapabilitiesMapping-150]
	_ = x[PrimitiveStaticTypeAccountMapping-151]
	_ = x[PrimitiveStaticType_Count-152]
}

const _PrimitiveStaticType_name = "UnknownVoidAnyNeverAnyStructAnyResourceBoolAddressStringCharacterMetaTypeBlockAnyResourceAttachmentAnyStructAttachmentHashableStructStorableInvalidNumberSignedNumberIntegerSignedIntegerFixedSizeUnsignedIntegerFixedPointSignedFixedPointIntInt8Int16Int32Int64Int128Int256UIntUInt8UInt16UInt32UInt64UInt128UInt256Word8Word16Word32Word64Word128Word256Fix64Fix128UFix64UFix128PathCapabilityStoragePathCapabilityPathPublicPathPrivatePathAuthAccountPublicAccountDeployedContractAuthAccountContractsPublicAccountContractsAuthAccountKeysPublicAccountKeysAccountKeyAuthAccountInboxStorageCapabilityControllerAccountCapabilityControllerAuthAccountStorageCapabilitiesAuthAccountAccountCapabilitiesAuthAccountCapabilitiesPublicAccountCapabilitiesAccountAccount_ContractsAccount_KeysAccount_InboxAccount_StorageCapabilitiesAccount_AccountCapabilitiesAccount_CapabilitiesAccount_StorageMutateInsertRemoveIdentityStorageSaveValueLoadValueCopyValueBorrowValueContractsAddContractUpdateContractRemoveContractKeysAddKeyRevokeKeyInboxPublishInboxCapabilityUnpublishInboxCapabilityClaimInboxCapabilityCapabilitiesStorageCapabilitiesAccountCapabilitiesPublishCapabilityUnpublishCapabilityGetStorageCapabilityControllerIssueStorageCapabilityControllerGetAccountCapabilityControllerIssueAccountCapabilityControllerCapabilitiesMappingAccountMapping_Count"

var _PrimitiveStaticType_map = map[PrimitiveStaticType]string{
	0:   _PrimitiveStaticType_name[0:7],
	1:   _PrimitiveStaticType_name[7:11],
	2:   _PrimitiveStaticType_name[11:14],
	3:   _PrimitiveStaticType_name[14:19],
	4:   _PrimitiveStaticType_name[19:28],
	5:   _PrimitiveStaticType_name[28:39],
	6:   _PrimitiveStaticType_name[39:43],
	7:   _PrimitiveStaticType_name[43:50],
	8:   _PrimitiveStaticType_name[50:56],
	9:   _PrimitiveStaticType_name[56:65],
	10:  _PrimitiveStaticType_name[65:73],
	11:  _PrimitiveStaticType_name[73:78],
	12:  _PrimitiveStaticType_name[78:99],
	13:  _PrimitiveStaticType_name[99:118],
	14:  _PrimitiveStaticType_name[118:132],
	15:  _PrimitiveStaticType_name[132:140],
	16:  _PrimitiveStaticType_name[140:147],
	18:  _PrimitiveStaticType_name[147:153],
	19:  _PrimitiveStaticType_name[153:165],
	24:  _PrimitiveStaticType_name[165:172],
	25:  _PrimitiveStaticType_name[172:185],
	26:  _PrimitiveStaticType_name[185:209],
	30:  _PrimitiveStaticType_name[209:219],
	31:  _PrimitiveStaticType_name[219:235],
	36:  _PrimitiveStaticType_name[235:238],
	37:  _PrimitiveStaticType_name[238:242],
	38:  _PrimitiveStaticType_name[242:247],
	39:  _PrimitiveStaticType_name[247:252],
	40:  _PrimitiveStaticType_name[252:257],
	41:  _PrimitiveStaticType_name[257:263],
	42:  _PrimitiveStaticType_name[263:269],
	44:  _PrimitiveStaticType_name[269:273],
	45:  _PrimitiveStaticType_name[273:278],
	46:  _PrimitiveStaticType_name[278:284],
	47:  _PrimitiveStaticType_name[284:290],
	48:  _PrimitiveStaticType_name[290:296],
	49:  _PrimitiveStaticType_name[296:303],
	50:  _PrimitiveStaticType_name[303:310],
	53:  _PrimitiveStaticType_name[310:315],
	54:  _PrimitiveStaticType_name[315:321],
	55:  _PrimitiveStaticType_name[321:327],
	56:  _PrimitiveStaticType_name[327:333],
	57:  _PrimitiveStaticType_name[333:340],
	58:  _PrimitiveStaticType_name[340:347],
	64:  _PrimitiveStaticType_name[347:352],
	65:  _PrimitiveStaticType_name[352:358],
	72:  _PrimitiveStaticType_name[358:364],
	73:  _PrimitiveStaticType_name[364:371],
	76:  _PrimitiveStaticType_name[371:375],
	77:  _PrimitiveStaticType_name[375:385],
	78:  _PrimitiveStaticType_name[385:396],
	79:  _PrimitiveStaticType_name[396:410],
	80:  _PrimitiveStaticType_name[410:420],
	81:  _PrimitiveStaticType_name[420:431],
	90:  _PrimitiveStaticType_name[431:442],
	91:  _PrimitiveStaticType_name[442:455],
	92:  _PrimitiveStaticType_name[455:471],
	93:  _PrimitiveStaticType_name[471:491],
	94:  _PrimitiveStaticType_name[491:513],
	95:  _PrimitiveStaticType_name[513:528],
	96:  _PrimitiveStaticType_name[528:545],
	97:  _PrimitiveStaticType_name[545:555],
	98:  _PrimitiveStaticType_name[555:571],
	99:  _PrimitiveStaticType_name[571:598],
	100: _PrimitiveStaticType_name[598:625],
	101: _PrimitiveStaticType_name[625:655],
	102: _PrimitiveStaticType_name[655:685],
	103: _PrimitiveStaticType_name[685:708],
	104: _PrimitiveStaticType_name[708:733],
	105: _PrimitiveStaticType_name[733:740],
	106: _PrimitiveStaticType_name[740:757],
	107: _PrimitiveStaticType_name[757:769],
	108: _PrimitiveStaticType_name[769:782],
	109: _PrimitiveStaticType_name[782:809],
	110: _PrimitiveStaticType_name[809:836],
	111: _PrimitiveStaticType_name[836:856],
	112: _PrimitiveStaticType_name[856:871],
	118: _PrimitiveStaticType_name[871:877],
	119: _PrimitiveStaticType_name[877:883],
	120: _PrimitiveStaticType_name[883:889],
	121: _PrimitiveStaticType_name[889:897],
	125: _PrimitiveStaticType_name[897:904],
	126: _PrimitiveStaticType_name[904:913],
	127: _PrimitiveStaticType_name[913:922],
	128: _PrimitiveStaticType_name[922:931],
	129: _PrimitiveStaticType_name[931:942],
	130: _PrimitiveStaticType_name[942:951],
	131: _PrimitiveStaticType_name[951:962],
	132: _PrimitiveStaticType_name[962:976],
	133: _PrimitiveStaticType_name[976:990],
	134: _PrimitiveStaticType_name[990:994],
	135: _PrimitiveStaticType_name[994:1000],
	136: _PrimitiveStaticType_name[1000:1009],
	137: _PrimitiveStaticType_name[1009:1014],
	138: _PrimitiveStaticType_name[1014:1036],
	139: _PrimitiveStaticType_name[1036:1060],
	140: _PrimitiveStaticType_name[1060:1080],
	141: _PrimitiveStaticType_name[1080:1092],
	142: _PrimitiveStaticType_name[1092:1111],
	143: _PrimitiveStaticType_name[1111:1130],
	144: _PrimitiveStaticType_name[1130:1147],
	145: _PrimitiveStaticType_name[1147:1166],
	146: _PrimitiveStaticType_name[1166:1196],
	147: _PrimitiveStaticType_name[1196:1228],
	148: _PrimitiveStaticType_name[1228:1258],
	149: _PrimitiveStaticType_name[1258:1290],
	150: _PrimitiveStaticType_name[1290:1309],
	151: _PrimitiveStaticType_name[1309:1323],
	152: _PrimitiveStaticType_name[1323:1329],
}

func (i PrimitiveStaticType) String() string {
	if str, ok := _PrimitiveStaticType_map[i]; ok {
		return str
	}
	return "PrimitiveStaticType(" + strconv.FormatInt(int64(i), 10) + ")"
}
