// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package opcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Return-1]
	_ = x[ReturnValue-2]
	_ = x[Jump-3]
	_ = x[JumpIfFalse-4]
	_ = x[IntAdd-5]
	_ = x[IntSubtract-6]
	_ = x[IntMultiply-7]
	_ = x[IntDivide-8]
	_ = x[IntMod-9]
	_ = x[IntLess-10]
	_ = x[IntGreater-11]
	_ = x[IntLessOrEqual-12]
	_ = x[IntGreaterOrEqual-13]
	_ = x[Equal-14]
	_ = x[NotEqual-15]
	_ = x[Unwrap-16]
	_ = x[Destroy-17]
	_ = x[Transfer-18]
	_ = x[Cast-19]
	_ = x[True-20]
	_ = x[False-21]
	_ = x[New-22]
	_ = x[Path-23]
	_ = x[Nil-24]
	_ = x[GetConstant-25]
	_ = x[GetLocal-26]
	_ = x[SetLocal-27]
	_ = x[GetGlobal-28]
	_ = x[SetGlobal-29]
	_ = x[GetField-30]
	_ = x[SetField-31]
	_ = x[Invoke-32]
	_ = x[InvokeDynamic-33]
	_ = x[Drop-34]
	_ = x[Dup-35]
}

const _Opcode_name = "UnknownReturnReturnValueJumpJumpIfFalseIntAddIntSubtractIntMultiplyIntDivideIntModIntLessIntGreaterIntLessOrEqualIntGreaterOrEqualEqualNotEqualUnwrapDestroyTransferCastTrueFalseNewPathNilGetConstantGetLocalSetLocalGetGlobalSetGlobalGetFieldSetFieldInvokeInvokeDynamicDropDup"

var _Opcode_index = [...]uint16{0, 7, 13, 24, 28, 39, 45, 56, 67, 76, 82, 89, 99, 113, 130, 135, 143, 149, 156, 164, 168, 172, 177, 180, 184, 187, 198, 206, 214, 223, 232, 240, 248, 254, 267, 271, 274}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
