// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package opcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Return-1]
	_ = x[ReturnValue-2]
	_ = x[Jump-3]
	_ = x[JumpIfFalse-4]
	_ = x[IntAdd-5]
	_ = x[IntSubtract-6]
	_ = x[IntMultiply-7]
	_ = x[IntDivide-8]
	_ = x[IntMod-9]
	_ = x[IntEqual-10]
	_ = x[IntNotEqual-11]
	_ = x[IntLess-12]
	_ = x[IntGreater-13]
	_ = x[IntLessOrEqual-14]
	_ = x[IntGreaterOrEqual-15]
	_ = x[Equal-16]
	_ = x[Unwrap-17]
	_ = x[GetConstant-18]
	_ = x[True-19]
	_ = x[False-20]
	_ = x[GetLocal-21]
	_ = x[SetLocal-22]
	_ = x[GetGlobal-23]
	_ = x[SetGlobal-24]
	_ = x[GetField-25]
	_ = x[SetField-26]
	_ = x[Invoke-27]
	_ = x[InvokeDynamic-28]
	_ = x[Destroy-29]
	_ = x[Transfer-30]
	_ = x[Cast-31]
	_ = x[New-32]
	_ = x[Path-33]
	_ = x[Nil-34]
	_ = x[Drop-35]
	_ = x[Dup-36]
	_ = x[Empty-37]
}

const _Opcode_name = "UnknownReturnReturnValueJumpJumpIfFalseIntAddIntSubtractIntMultiplyIntDivideIntModIntEqualIntNotEqualIntLessIntGreaterIntLessOrEqualIntGreaterOrEqualEqualUnwrapGetConstantTrueFalseGetLocalSetLocalGetGlobalSetGlobalGetFieldSetFieldInvokeInvokeDynamicDestroyTransferCastNewPathNilDropDupEmpty"

var _Opcode_index = [...]uint16{0, 7, 13, 24, 28, 39, 45, 56, 67, 76, 82, 90, 101, 108, 118, 132, 149, 154, 160, 171, 175, 180, 188, 196, 205, 214, 222, 230, 236, 249, 256, 264, 268, 271, 275, 278, 282, 285, 290}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
