// Code generated by "stringer -type=CBORTag -trimprefix=CBORTag"; DO NOT EDIT.

package ccf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CBORTagTypeDef-128]
	_ = x[CBORTagTypeDefAndValue-129]
	_ = x[CBORTagTypeAndValue-130]
	_ = x[CBORTagTypeRef-136]
	_ = x[CBORTagSimpleType-137]
	_ = x[CBORTagOptionalType-138]
	_ = x[CBORTagVarsizedArrayType-139]
	_ = x[CBORTagConstsizedArrayType-140]
	_ = x[CBORTagDictType-141]
	_ = x[CBORTagReferenceType-142]
	_ = x[CBORTagIntersectionType-143]
	_ = x[CBORTagCapabilityType-144]
	_ = x[CBORTagInclusiveRangeType-145]
	_ = x[CBORTagEntitlementSetAuthorizationAccessType-146]
	_ = x[CBORTagEntitlementMapAuthorizationAccessType-147]
	_ = x[CBORTagStructType-160]
	_ = x[CBORTagResourceType-161]
	_ = x[CBORTagEventType-162]
	_ = x[CBORTagContractType-163]
	_ = x[CBORTagEnumType-164]
	_ = x[CBORTagAttachmentType-165]
	_ = x[CBORTagStructInterfaceType-176]
	_ = x[CBORTagResourceInterfaceType-177]
	_ = x[CBORTagContractInterfaceType-178]
	_ = x[CBORTagTypeValueRef-184]
	_ = x[CBORTagSimpleTypeValue-185]
	_ = x[CBORTagOptionalTypeValue-186]
	_ = x[CBORTagVarsizedArrayTypeValue-187]
	_ = x[CBORTagConstsizedArrayTypeValue-188]
	_ = x[CBORTagDictTypeValue-189]
	_ = x[CBORTagReferenceTypeValue-190]
	_ = x[CBORTagIntersectionTypeValue-191]
	_ = x[CBORTagCapabilityTypeValue-192]
	_ = x[CBORTagFunctionTypeValue-193]
	_ = x[CBORTagInclusiveRangeTypeValue-194]
	_ = x[CBORTagEntitlementSetAuthorizationAccessTypeValue-195]
	_ = x[CBORTagEntitlementMapAuthorizationAccessTypeValue-196]
	_ = x[CBORTagStructTypeValue-208]
	_ = x[CBORTagResourceTypeValue-209]
	_ = x[CBORTagEventTypeValue-210]
	_ = x[CBORTagContractTypeValue-211]
	_ = x[CBORTagEnumTypeValue-212]
	_ = x[CBORTagAttachmentTypeValue-213]
	_ = x[CBORTagStructInterfaceTypeValue-224]
	_ = x[CBORTagResourceInterfaceTypeValue-225]
	_ = x[CBORTagContractInterfaceTypeValue-226]
	_ = x[CBORTag_Count-232]
}

const (
	_CBORTag_name_0 = "TypeDefTypeDefAndValueTypeAndValue"
	_CBORTag_name_1 = "TypeRefSimpleTypeOptionalTypeVarsizedArrayTypeConstsizedArrayTypeDictTypeReferenceTypeIntersectionTypeCapabilityTypeInclusiveRangeTypeEntitlementSetAuthorizationAccessTypeEntitlementMapAuthorizationAccessType"
	_CBORTag_name_2 = "StructTypeResourceTypeEventTypeContractTypeEnumTypeAttachmentType"
	_CBORTag_name_3 = "StructInterfaceTypeResourceInterfaceTypeContractInterfaceType"
	_CBORTag_name_4 = "TypeValueRefSimpleTypeValueOptionalTypeValueVarsizedArrayTypeValueConstsizedArrayTypeValueDictTypeValueReferenceTypeValueIntersectionTypeValueCapabilityTypeValueFunctionTypeValueInclusiveRangeTypeValueEntitlementSetAuthorizationAccessTypeValueEntitlementMapAuthorizationAccessTypeValue"
	_CBORTag_name_5 = "StructTypeValueResourceTypeValueEventTypeValueContractTypeValueEnumTypeValueAttachmentTypeValue"
	_CBORTag_name_6 = "StructInterfaceTypeValueResourceInterfaceTypeValueContractInterfaceTypeValue"
	_CBORTag_name_7 = "_Count"
)

var (
	_CBORTag_index_0 = [...]uint8{0, 7, 22, 34}
	_CBORTag_index_1 = [...]uint8{0, 7, 17, 29, 46, 65, 73, 86, 102, 116, 134, 171, 208}
	_CBORTag_index_2 = [...]uint8{0, 10, 22, 31, 43, 51, 65}
	_CBORTag_index_3 = [...]uint8{0, 19, 40, 61}
	_CBORTag_index_4 = [...]uint16{0, 12, 27, 44, 66, 90, 103, 121, 142, 161, 178, 201, 243, 285}
	_CBORTag_index_5 = [...]uint8{0, 15, 32, 46, 63, 76, 95}
	_CBORTag_index_6 = [...]uint8{0, 24, 50, 76}
)

func (i CBORTag) String() string {
	switch {
	case 128 <= i && i <= 130:
		i -= 128
		return _CBORTag_name_0[_CBORTag_index_0[i]:_CBORTag_index_0[i+1]]
	case 136 <= i && i <= 147:
		i -= 136
		return _CBORTag_name_1[_CBORTag_index_1[i]:_CBORTag_index_1[i+1]]
	case 160 <= i && i <= 165:
		i -= 160
		return _CBORTag_name_2[_CBORTag_index_2[i]:_CBORTag_index_2[i+1]]
	case 176 <= i && i <= 178:
		i -= 176
		return _CBORTag_name_3[_CBORTag_index_3[i]:_CBORTag_index_3[i+1]]
	case 184 <= i && i <= 196:
		i -= 184
		return _CBORTag_name_4[_CBORTag_index_4[i]:_CBORTag_index_4[i+1]]
	case 208 <= i && i <= 213:
		i -= 208
		return _CBORTag_name_5[_CBORTag_index_5[i]:_CBORTag_index_5[i+1]]
	case 224 <= i && i <= 226:
		i -= 224
		return _CBORTag_name_6[_CBORTag_index_6[i]:_CBORTag_index_6[i+1]]
	case i == 232:
		return _CBORTag_name_7
	default:
		return "CBORTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
