// Code generated by "stringer -type=SimpleType"; DO NOT EDIT.

package ccf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SimpleTypeBool-0]
	_ = x[SimpleTypeString-1]
	_ = x[SimpleTypeCharacter-2]
	_ = x[SimpleTypeAddress-3]
	_ = x[SimpleTypeInt-4]
	_ = x[SimpleTypeInt8-5]
	_ = x[SimpleTypeInt16-6]
	_ = x[SimpleTypeInt32-7]
	_ = x[SimpleTypeInt64-8]
	_ = x[SimpleTypeInt128-9]
	_ = x[SimpleTypeInt256-10]
	_ = x[SimpleTypeUInt-11]
	_ = x[SimpleTypeUInt8-12]
	_ = x[SimpleTypeUInt16-13]
	_ = x[SimpleTypeUInt32-14]
	_ = x[SimpleTypeUInt64-15]
	_ = x[SimpleTypeUInt128-16]
	_ = x[SimpleTypeUInt256-17]
	_ = x[SimpleTypeWord8-18]
	_ = x[SimpleTypeWord16-19]
	_ = x[SimpleTypeWord32-20]
	_ = x[SimpleTypeWord64-21]
	_ = x[SimpleTypeFix64-22]
	_ = x[SimpleTypeUFix64-23]
	_ = x[SimpleTypePath-24]
	_ = x[SimpleTypeCapabilityPath-25]
	_ = x[SimpleTypeStoragePath-26]
	_ = x[SimpleTypePublicPath-27]
	_ = x[SimpleTypePrivatePath-28]
	_ = x[SimpleTypeDeployedContract-35]
	_ = x[SimpleTypeBlock-37]
	_ = x[SimpleTypeAny-38]
	_ = x[SimpleTypeAnyStruct-39]
	_ = x[SimpleTypeAnyResource-40]
	_ = x[SimpleTypeMetaType-41]
	_ = x[SimpleTypeNever-42]
	_ = x[SimpleTypeNumber-43]
	_ = x[SimpleTypeSignedNumber-44]
	_ = x[SimpleTypeInteger-45]
	_ = x[SimpleTypeSignedInteger-46]
	_ = x[SimpleTypeFixedPoint-47]
	_ = x[SimpleTypeSignedFixedPoint-48]
	_ = x[SimpleTypeBytes-49]
	_ = x[SimpleTypeVoid-50]
	_ = x[SimpleTypeFunction-51]
	_ = x[SimpleTypeWord128-52]
	_ = x[SimpleTypeWord256-53]
	_ = x[SimpleTypeAnyStructAttachmentType-54]
	_ = x[SimpleTypeAnyResourceAttachmentType-55]
	_ = x[SimpleTypeStorageCapabilityController-56]
	_ = x[SimpleTypeAccountCapabilityController-57]
	_ = x[SimpleTypeAccount-58]
	_ = x[SimpleTypeAccount_Contracts-59]
	_ = x[SimpleTypeAccount_Keys-60]
	_ = x[SimpleTypeAccount_Inbox-61]
	_ = x[SimpleTypeAccount_StorageCapabilities-62]
	_ = x[SimpleTypeAccount_AccountCapabilities-63]
	_ = x[SimpleTypeAccount_Capabilities-64]
	_ = x[SimpleTypeAccount_Storage-65]
	_ = x[SimpleTypeMutate-66]
	_ = x[SimpleTypeInsert-67]
	_ = x[SimpleTypeRemove-68]
	_ = x[SimpleTypeIdentity-69]
	_ = x[SimpleTypeStorage-70]
	_ = x[SimpleTypeSaveValue-71]
	_ = x[SimpleTypeLoadValue-72]
	_ = x[SimpleTypeBorrowValue-73]
	_ = x[SimpleTypeContracts-74]
	_ = x[SimpleTypeAddContract-75]
	_ = x[SimpleTypeUpdateContract-76]
	_ = x[SimpleTypeRemoveContract-77]
	_ = x[SimpleTypeKeys-78]
	_ = x[SimpleTypeAddKey-79]
	_ = x[SimpleTypeRevokeKey-80]
	_ = x[SimpleTypeInbox-81]
	_ = x[SimpleTypePublishInboxCapability-82]
	_ = x[SimpleTypeUnpublishInboxCapability-83]
	_ = x[SimpleTypeClaimInboxCapability-84]
	_ = x[SimpleTypeCapabilities-85]
	_ = x[SimpleTypeStorageCapabilities-86]
	_ = x[SimpleTypeAccountCapabilities-87]
	_ = x[SimpleTypePublishCapability-88]
	_ = x[SimpleTypeUnpublishCapability-89]
	_ = x[SimpleTypeGetStorageCapabilityController-90]
	_ = x[SimpleTypeIssueStorageCapabilityController-91]
	_ = x[SimpleTypeGetAccountCapabilityController-92]
	_ = x[SimpleTypeIssueAccountCapabilityController-93]
	_ = x[SimpleTypeCapabilitiesMapping-94]
	_ = x[SimpleTypeAccountMapping-95]
	_ = x[SimpleType_Count-96]
}

const (
	_SimpleType_name_0 = "SimpleTypeBoolSimpleTypeStringSimpleTypeCharacterSimpleTypeAddressSimpleTypeIntSimpleTypeInt8SimpleTypeInt16SimpleTypeInt32SimpleTypeInt64SimpleTypeInt128SimpleTypeInt256SimpleTypeUIntSimpleTypeUInt8SimpleTypeUInt16SimpleTypeUInt32SimpleTypeUInt64SimpleTypeUInt128SimpleTypeUInt256SimpleTypeWord8SimpleTypeWord16SimpleTypeWord32SimpleTypeWord64SimpleTypeFix64SimpleTypeUFix64SimpleTypePathSimpleTypeCapabilityPathSimpleTypeStoragePathSimpleTypePublicPathSimpleTypePrivatePath"
	_SimpleType_name_1 = "SimpleTypeDeployedContract"
	_SimpleType_name_2 = "SimpleTypeBlockSimpleTypeAnySimpleTypeAnyStructSimpleTypeAnyResourceSimpleTypeMetaTypeSimpleTypeNeverSimpleTypeNumberSimpleTypeSignedNumberSimpleTypeIntegerSimpleTypeSignedIntegerSimpleTypeFixedPointSimpleTypeSignedFixedPointSimpleTypeBytesSimpleTypeVoidSimpleTypeFunctionSimpleTypeWord128SimpleTypeWord256SimpleTypeAnyStructAttachmentTypeSimpleTypeAnyResourceAttachmentTypeSimpleTypeStorageCapabilityControllerSimpleTypeAccountCapabilityControllerSimpleTypeAccountSimpleTypeAccount_ContractsSimpleTypeAccount_KeysSimpleTypeAccount_InboxSimpleTypeAccount_StorageCapabilitiesSimpleTypeAccount_AccountCapabilitiesSimpleTypeAccount_CapabilitiesSimpleTypeAccount_StorageSimpleTypeMutateSimpleTypeInsertSimpleTypeRemoveSimpleTypeIdentitySimpleTypeStorageSimpleTypeSaveValueSimpleTypeLoadValueSimpleTypeBorrowValueSimpleTypeContractsSimpleTypeAddContractSimpleTypeUpdateContractSimpleTypeRemoveContractSimpleTypeKeysSimpleTypeAddKeySimpleTypeRevokeKeySimpleTypeInboxSimpleTypePublishInboxCapabilitySimpleTypeUnpublishInboxCapabilitySimpleTypeClaimInboxCapabilitySimpleTypeCapabilitiesSimpleTypeStorageCapabilitiesSimpleTypeAccountCapabilitiesSimpleTypePublishCapabilitySimpleTypeUnpublishCapabilitySimpleTypeGetStorageCapabilityControllerSimpleTypeIssueStorageCapabilityControllerSimpleTypeGetAccountCapabilityControllerSimpleTypeIssueAccountCapabilityControllerSimpleTypeCapabilitiesMappingSimpleTypeAccountMappingSimpleType_Count"
)

var (
	_SimpleType_index_0 = [...]uint16{0, 14, 30, 49, 66, 79, 93, 108, 123, 138, 154, 170, 184, 199, 215, 231, 247, 264, 281, 296, 312, 328, 344, 359, 375, 389, 413, 434, 454, 475}
	_SimpleType_index_2 = [...]uint16{0, 15, 28, 47, 68, 86, 101, 117, 139, 156, 179, 199, 225, 240, 254, 272, 289, 306, 339, 374, 411, 448, 465, 492, 514, 537, 574, 611, 641, 666, 682, 698, 714, 732, 749, 768, 787, 808, 827, 848, 872, 896, 910, 926, 945, 960, 992, 1026, 1056, 1078, 1107, 1136, 1163, 1192, 1232, 1274, 1314, 1356, 1385, 1409, 1425}
)

func (i SimpleType) String() string {
	switch {
	case i <= 28:
		return _SimpleType_name_0[_SimpleType_index_0[i]:_SimpleType_index_0[i+1]]
	case i == 35:
		return _SimpleType_name_1
	case 37 <= i && i <= 96:
		i -= 37
		return _SimpleType_name_2[_SimpleType_index_2[i]:_SimpleType_index_2[i+1]]
	default:
		return "SimpleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
