name: "Private Build Setup"
description: "Checks and configures the environment for building private dependencies"
inputs:
  atree_deploy_key:
    description: "Deploy Key for Private Atree Repo"
    required: true
  go_private_value:
    description: "The value for GOPRIVATE"
    required: false
    default: "github.com/onflow/atree-internal"
runs:
  using: "composite"
  steps:
    - name: Load atree deploy key
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: "${{ inputs.atree_deploy_key }}"

    - name: Configure git for SSH
      shell: bash
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Configure GOPRIVATE env
      shell: bash
      run: |
        echo "GOPRIVATE=${{ inputs.go_private_value }}" >> $GITHUB_ENV
