// Code generated by "stringer -type=DeclarationKind"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeclarationKindValue-0]
	_ = x[DeclarationKindFunction-1]
	_ = x[DeclarationKindVariable-2]
	_ = x[DeclarationKindConstant-3]
	_ = x[DeclarationKindType-4]
}

const _DeclarationKind_name = "DeclarationKindValueDeclarationKindFunctionDeclarationKindVariableDeclarationKindConstantDeclarationKindType"

var _DeclarationKind_index = [...]uint8{0, 20, 43, 66, 89, 108}

func (i DeclarationKind) String() string {
	if i < 0 || i >= DeclarationKind(len(_DeclarationKind_index)-1) {
		return "DeclarationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeclarationKind_name[_DeclarationKind_index[i]:_DeclarationKind_index[i+1]]
}
