// Code generated by "stringer -type=AccessCheckMode"; DO NOT EDIT.

package sema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessCheckModeDefault-0]
	_ = x[AccessCheckModeStrict-1]
	_ = x[AccessCheckModeNotSpecifiedRestricted-2]
	_ = x[AccessCheckModeNotSpecifiedUnrestricted-3]
	_ = x[AccessCheckModeNone-4]
}

const _AccessCheckMode_name = "AccessCheckModeDefaultAccessCheckModeStrictAccessCheckModeNotSpecifiedRestrictedAccessCheckModeNotSpecifiedUnrestrictedAccessCheckModeNone"

var _AccessCheckMode_index = [...]uint8{0, 22, 43, 80, 119, 138}

func (i AccessCheckMode) String() string {
	if i >= AccessCheckMode(len(_AccessCheckMode_index)-1) {
		return "AccessCheckMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessCheckMode_name[_AccessCheckMode_index[i]:_AccessCheckMode_index[i+1]]
}
