// Code generated by "stringer -type=AccessCheckMode"; DO NOT EDIT.

package sema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessCheckModeStrict-0]
	_ = x[AccessCheckModeNotSpecifiedRestricted-1]
	_ = x[AccessCheckModeNotSpecifiedUnrestricted-2]
	_ = x[AccessCheckModeNone-3]
}

const _AccessCheckMode_name = "AccessCheckModeStrictAccessCheckModeNotSpecifiedRestrictedAccessCheckModeNotSpecifiedUnrestrictedAccessCheckModeNone"

var _AccessCheckMode_index = [...]uint8{0, 21, 58, 97, 116}

func (i AccessCheckMode) String() string {
	if i >= AccessCheckMode(len(_AccessCheckMode_index)-1) {
		return "AccessCheckMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessCheckMode_name[_AccessCheckMode_index[i]:_AccessCheckMode_index[i+1]]
}
