/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=BinaryOperationKind"; DO NOT EDIT.

package sema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinaryOperationKindUnknown-0]
	_ = x[BinaryOperationKindArithmetic-1]
	_ = x[BinaryOperationKindNonEqualityComparison-2]
	_ = x[BinaryOperationKindBooleanLogic-3]
	_ = x[BinaryOperationKindEquality-4]
	_ = x[BinaryOperationKindNilCoalescing-5]
	_ = x[BinaryOperationKindConcatenation-6]
}

const _BinaryOperationKind_name = "BinaryOperationKindUnknownBinaryOperationKindArithmeticBinaryOperationKindNonEqualityComparisonBinaryOperationKindBooleanLogicBinaryOperationKindEqualityBinaryOperationKindNilCoalescingBinaryOperationKindConcatenation"

var _BinaryOperationKind_index = [...]uint8{0, 26, 55, 95, 126, 153, 185, 217}

func (i BinaryOperationKind) String() string {
	if i < 0 || i >= BinaryOperationKind(len(_BinaryOperationKind_index)-1) {
		return "BinaryOperationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperationKind_name[_BinaryOperationKind_index[i]:_BinaryOperationKind_index[i+1]]
}
