// Code generated by "stringer -type=HashAlgorithm"; DO NOT EDIT.

package sema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashAlgorithmSHA2_256-0]
	_ = x[HashAlgorithmSHA3_256-1]
}

const _HashAlgorithm_name = "HashAlgorithmSHA2_256HashAlgorithmSHA3_256"

var _HashAlgorithm_index = [...]uint8{0, 21, 42}

func (i HashAlgorithm) String() string {
	if i < 0 || i >= HashAlgorithm(len(_HashAlgorithm_index)-1) {
		return "HashAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashAlgorithm_name[_HashAlgorithm_index[i]:_HashAlgorithm_index[i+1]]
}
