/*
 * Cadence - The resource-oriented smart contract programming language
 *
 * Copyright 2019-2020 Dapper Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=TypeAnnotationState"; DO NOT EDIT.

package sema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeAnnotationStateUnknown-0]
	_ = x[TypeAnnotationStateValid-1]
	_ = x[TypeAnnotationStateInvalidResourceAnnotation-2]
	_ = x[TypeAnnotationStateMissingResourceAnnotation-3]
}

const _TypeAnnotationState_name = "TypeAnnotationStateUnknownTypeAnnotationStateValidTypeAnnotationStateInvalidResourceAnnotationTypeAnnotationStateMissingResourceAnnotation"

var _TypeAnnotationState_index = [...]uint8{0, 26, 50, 94, 138}

func (i TypeAnnotationState) String() string {
	if i < 0 || i >= TypeAnnotationState(len(_TypeAnnotationState_index)-1) {
		return "TypeAnnotationState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeAnnotationState_name[_TypeAnnotationState_index[i]:_TypeAnnotationState_index[i+1]]
}
