// Code generated by "stringer -type=AccessLevel"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLevelPrivate-0]
	_ = x[AccessLevelPublic-1]
}

const _AccessLevel_name = "AccessLevelPrivateAccessLevelPublic"

var _AccessLevel_index = [...]uint8{0, 18, 35}

func (i AccessLevel) String() string {
	if i < 0 || i >= AccessLevel(len(_AccessLevel_index)-1) {
		return "AccessLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessLevel_name[_AccessLevel_index[i]:_AccessLevel_index[i+1]]
}
